# Generated by Django 4.2.2 on 2023-06-26 18:38

import alarm_system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm_system',
            name='maintenance_report',
            field=models.ImageField(blank=True, null=True, upload_to=alarm_system.models.maintenance_report_directory_path, verbose_name='maintenance_report'),
        ),
    ]
