# Generated by Django 4.2.2 on 2023-06-24 19:46

from django.db import migrations, models
import worker.models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform', '0002_alter_uniform_options'),
        ('briefing', '0001_initial'),
        ('document', '0002_alter_document_options'),
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Worker', 'verbose_name_plural': 'Workers'},
        ),
        migrations.AddField(
            model_name='worker',
            name='briefings',
            field=models.ManyToManyField(related_name='briefings', to='briefing.briefing', verbose_name='briefings'),
        ),
        migrations.AddField(
            model_name='worker',
            name='category',
            field=models.SmallIntegerField(db_index=True, default=0, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='worker',
            name='data_employment',
            field=models.CharField(db_index=True, default=1, max_length=10, verbose_name='data_employment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='date_birth',
            field=models.CharField(db_index=True, default=1, max_length=10, verbose_name='date_birth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='department',
            field=models.CharField(db_index=True, default=1, max_length=25, verbose_name='department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='documents',
            field=models.ManyToManyField(related_name='documents', to='document.document', verbose_name='documents'),
        ),
        migrations.AddField(
            model_name='worker',
            name='electrical_safety_qualification',
            field=models.SmallIntegerField(db_index=True, default=0, verbose_name='electrical_safety_qualification'),
        ),
        migrations.AddField(
            model_name='worker',
            name='first_name',
            field=models.CharField(db_index=True, default=1, max_length=30, verbose_name='first_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=worker.models.foto_directory_path, verbose_name='foto'),
        ),
        migrations.AddField(
            model_name='worker',
            name='middle_name',
            field=models.CharField(db_index=True, default=1, max_length=30, verbose_name='middle_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='position',
            field=models.CharField(db_index=True, default=1, max_length=30, verbose_name='position'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='second_name',
            field=models.CharField(db_index=True, default=1, max_length=50, verbose_name='second_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='uniforms',
            field=models.ManyToManyField(related_name='uniforms', to='uniform.uniform', verbose_name='uniforms'),
        ),
    ]
