# Generated by Django 4.2.2 on 2023-06-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_alter_worker_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='phone',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, default=0, help_text='format phone: 83517772233', null=True, verbose_name='phone'),
        ),
    ]
