# Generated by Django 4.2.2 on 2023-06-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_alter_worker_options_worker_briefings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='archived'),
        ),
    ]
