# Generated by Django 4.2.2 on 2023-06-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_worker_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='category',
            field=models.SmallIntegerField(blank=True, db_index=True, default=0, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='data_employment',
            field=models.CharField(db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, verbose_name='data_employment'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='date_birth',
            field=models.CharField(db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, verbose_name='date_birth'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='electrical_safety_qualification',
            field=models.SmallIntegerField(blank=True, db_index=True, default=0, verbose_name='electrical_safety_qualification'),
        ),
    ]
