# Generated by Django 4.2.2 on 2023-06-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_alter_worker_category_alter_worker_data_employment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='address',
            field=models.CharField(db_index=True, default=1, max_length=150, verbose_name='address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='phone',
            field=models.CharField(db_index=True, default=1, help_text='format data: +70001112233', max_length=12, verbose_name='phone'),
            preserve_default=False,
        ),
    ]
