# Generated by Django 4.2.2 on 2023-06-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0005_worker_address_worker_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='size_clothing',
            field=models.SmallIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='size_clothing'),
        ),
        migrations.AddField(
            model_name='worker',
            name='size_hat',
            field=models.SmallIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='size_hat'),
        ),
        migrations.AddField(
            model_name='worker',
            name='size_shoe',
            field=models.SmallIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='size_shoe'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='category',
            field=models.SmallIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='electrical_safety_qualification',
            field=models.SmallIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='electrical_safety_qualification'),
        ),
    ]
