# Generated by Django 4.2.2 on 2023-07-02 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webcam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='name_webcam')),
                ('description', models.CharField(db_index=True, max_length=100, verbose_name='description')),
                ('factory_number', models.CharField(db_index=True, max_length=15, verbose_name='factory_number')),
                ('installation_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='installation_date')),
                ('maintenance_interval', models.CharField(db_index=True, max_length=15, verbose_name='maintenance_interval')),
                ('date_manufacture', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='date_manufacture')),
                ('receipt_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='receipt_date')),
                ('service_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='service_date')),
                ('service_date_next', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='service_date_next')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.affiliated_company')),
            ],
            options={
                'verbose_name': 'Webcam',
                'verbose_name_plural': 'Webcams',
            },
        ),
        migrations.CreateModel(
            name='Security_system',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='name')),
                ('description', models.CharField(db_index=True, max_length=100, verbose_name='description')),
                ('factory_number', models.CharField(db_index=True, max_length=15, verbose_name='factory_number')),
                ('installation_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='installation_date')),
                ('maintenance_interval', models.CharField(db_index=True, max_length=15, verbose_name='maintenance_interval')),
                ('date_manufacture', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='date_manufacture')),
                ('receipt_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='receipt_date')),
                ('service_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='service_date')),
                ('service_date_next', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='service_date')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.affiliated_company')),
            ],
            options={
                'verbose_name': 'Security_system',
                'verbose_name_plural': 'Security_systems',
            },
        ),
        migrations.CreateModel(
            name='Alarm_system',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='name')),
                ('description', models.CharField(db_index=True, max_length=100, verbose_name='description')),
                ('factory_number', models.CharField(db_index=True, max_length=15, verbose_name='factory_number')),
                ('installation_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='installation_date')),
                ('maintenance_interval', models.CharField(db_index=True, max_length=15, verbose_name='maintenance_interval')),
                ('date_manufacture', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='date_manufacture')),
                ('receipt_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='receipt_date')),
                ('service_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='service_date')),
                ('service_date_next', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='service_date_next')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.affiliated_company')),
            ],
            options={
                'verbose_name': 'Alarm_system',
                'verbose_name_plural': 'Alarm_systems',
            },
        ),
    ]
