# Generated by Django 4.2.2 on 2023-06-26 20:41

from django.db import migrations, models
import security_system.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm_system',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='name_alarm_system')),
                ('description', models.CharField(db_index=True, max_length=100, verbose_name='description_alarm_system')),
                ('factory_number', models.CharField(db_index=True, max_length=15, verbose_name='factory_number_alarm_system')),
                ('certificate', models.ImageField(blank=True, null=True, upload_to=security_system.models.certificate_directory_path, verbose_name='certificate_alarm_system')),
                ('installation_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='installation_date_alarm_system')),
                ('installation_report', models.ImageField(blank=True, null=True, upload_to=security_system.models.installation_report_directory_path, verbose_name='installation_report_alarm_system')),
                ('maintenance_interval', models.CharField(db_index=True, max_length=15, verbose_name='maintenance_interval_alarm_system')),
                ('date_manufacture', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='date_manufacture_alarm_system')),
                ('receipt_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='receipt_date_alarm_system')),
                ('service_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='service_date_alarm_system')),
                ('service_date_next', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='service_date_next_alarm_system')),
                ('maintenance_report', models.ImageField(blank=True, null=True, upload_to=security_system.models.maintenance_report_directory_path, verbose_name='maintenance_report_alarm_system')),
            ],
            options={
                'verbose_name': 'Alarm_system',
                'verbose_name_plural': 'Alarm_systems',
            },
        ),
        migrations.CreateModel(
            name='Security_system',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='name_security_system')),
                ('description', models.CharField(db_index=True, max_length=100, verbose_name='description_security_system')),
                ('factory_number', models.CharField(db_index=True, max_length=15, verbose_name='factory_number_security_system')),
                ('certificate', models.ImageField(blank=True, null=True, upload_to=security_system.models.certificate_directory_path, verbose_name='certificate_security_system')),
                ('installation_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='installation_date_security_system')),
                ('installation_report', models.ImageField(blank=True, null=True, upload_to=security_system.models.installation_report_directory_path, verbose_name='installation_report_security_system')),
                ('maintenance_interval', models.CharField(db_index=True, max_length=15, verbose_name='maintenance_interval_security_system')),
                ('date_manufacture', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='date_manufacture_security_system')),
                ('receipt_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='receipt_date_security_system')),
                ('service_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='service_date_security_system')),
                ('service_date_next', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='service_date_security_system')),
                ('maintenance_report', models.ImageField(blank=True, null=True, upload_to=security_system.models.maintenance_report_directory_path, verbose_name='maintenance_report_security_system')),
            ],
            options={
                'verbose_name': 'Security_system',
                'verbose_name_plural': 'Security_systems',
            },
        ),
        migrations.CreateModel(
            name='Webcam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='name_webcam')),
                ('description', models.CharField(db_index=True, max_length=100, verbose_name='description_webcam')),
                ('factory_number', models.CharField(db_index=True, max_length=15, verbose_name='factory_number_webcam')),
                ('certificate', models.ImageField(blank=True, null=True, upload_to=security_system.models.certificate_directory_path, verbose_name='certificate_webcam')),
                ('installation_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='installation_date_webcam')),
                ('installation_report', models.ImageField(blank=True, null=True, upload_to=security_system.models.installation_report_directory_path, verbose_name='installation_report_webcam')),
                ('maintenance_interval', models.CharField(db_index=True, max_length=15, verbose_name='maintenance_interval_webcam')),
                ('date_manufacture', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='date_manufacture_webcam')),
                ('receipt_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='receipt_date_webcam')),
                ('service_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='service_date_webcam')),
                ('service_date_next', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='service_date_next_webcam')),
                ('maintenance_report', models.ImageField(blank=True, null=True, upload_to=security_system.models.maintenance_report_directory_path, verbose_name='maintenance_report_webcam')),
            ],
            options={
                'verbose_name': 'Webcam',
                'verbose_name_plural': 'Webcams',
            },
        ),
    ]
