# Generated by Django 4.2.2 on 2023-06-28 19:21

from django.db import migrations, models
import security_system.models


class Migration(migrations.Migration):

    dependencies = [
        ('security_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm_system',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to=security_system.models.certificate_directory_path, verbose_name='certificate'),
        ),
        migrations.AlterField(
            model_name='alarm_system',
            name='date_manufacture',
            field=models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='date_manufacture'),
        ),
        migrations.AlterField(
            model_name='alarm_system',
            name='description',
            field=models.CharField(db_index=True, max_length=100, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='alarm_system',
            name='factory_number',
            field=models.CharField(db_index=True, max_length=15, verbose_name='factory_number'),
        ),
        migrations.AlterField(
            model_name='alarm_system',
            name='installation_date',
            field=models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='installation_date'),
        ),
        migrations.AlterField(
            model_name='alarm_system',
            name='installation_report',
            field=models.ImageField(blank=True, null=True, upload_to=security_system.models.installation_report_directory_path, verbose_name='installation_report'),
        ),
        migrations.AlterField(
            model_name='alarm_system',
            name='maintenance_interval',
            field=models.CharField(db_index=True, max_length=15, verbose_name='maintenance_interval'),
        ),
        migrations.AlterField(
            model_name='alarm_system',
            name='maintenance_report',
            field=models.ImageField(blank=True, null=True, upload_to=security_system.models.maintenance_report_directory_path, verbose_name='maintenance_report'),
        ),
        migrations.AlterField(
            model_name='alarm_system',
            name='name',
            field=models.CharField(db_index=True, max_length=20, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='alarm_system',
            name='receipt_date',
            field=models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='receipt_date'),
        ),
        migrations.AlterField(
            model_name='alarm_system',
            name='service_date',
            field=models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='service_date'),
        ),
        migrations.AlterField(
            model_name='alarm_system',
            name='service_date_next',
            field=models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='service_date_next'),
        ),
        migrations.AlterField(
            model_name='security_system',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to=security_system.models.certificate_directory_path, verbose_name='certificate'),
        ),
        migrations.AlterField(
            model_name='security_system',
            name='date_manufacture',
            field=models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='date_manufacture'),
        ),
        migrations.AlterField(
            model_name='security_system',
            name='description',
            field=models.CharField(db_index=True, max_length=100, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='security_system',
            name='factory_number',
            field=models.CharField(db_index=True, max_length=15, verbose_name='factory_number'),
        ),
        migrations.AlterField(
            model_name='security_system',
            name='installation_date',
            field=models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='installation_date'),
        ),
        migrations.AlterField(
            model_name='security_system',
            name='installation_report',
            field=models.ImageField(blank=True, null=True, upload_to=security_system.models.installation_report_directory_path, verbose_name='installation_report'),
        ),
        migrations.AlterField(
            model_name='security_system',
            name='maintenance_interval',
            field=models.CharField(db_index=True, max_length=15, verbose_name='maintenance_interval'),
        ),
        migrations.AlterField(
            model_name='security_system',
            name='maintenance_report',
            field=models.ImageField(blank=True, null=True, upload_to=security_system.models.maintenance_report_directory_path, verbose_name='maintenance_report'),
        ),
        migrations.AlterField(
            model_name='security_system',
            name='name',
            field=models.CharField(db_index=True, max_length=20, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='security_system',
            name='receipt_date',
            field=models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='receipt_date'),
        ),
        migrations.AlterField(
            model_name='security_system',
            name='service_date',
            field=models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='service_date'),
        ),
        migrations.AlterField(
            model_name='security_system',
            name='service_date_next',
            field=models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='service_date'),
        ),
        migrations.AlterField(
            model_name='webcam',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to=security_system.models.certificate_directory_path, verbose_name='certificate'),
        ),
        migrations.AlterField(
            model_name='webcam',
            name='date_manufacture',
            field=models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='date_manufacture'),
        ),
        migrations.AlterField(
            model_name='webcam',
            name='description',
            field=models.CharField(db_index=True, max_length=100, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='webcam',
            name='factory_number',
            field=models.CharField(db_index=True, max_length=15, verbose_name='factory_number'),
        ),
        migrations.AlterField(
            model_name='webcam',
            name='installation_date',
            field=models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='installation_date'),
        ),
        migrations.AlterField(
            model_name='webcam',
            name='installation_report',
            field=models.ImageField(blank=True, null=True, upload_to=security_system.models.installation_report_directory_path, verbose_name='installation_report'),
        ),
        migrations.AlterField(
            model_name='webcam',
            name='maintenance_interval',
            field=models.CharField(db_index=True, max_length=15, verbose_name='maintenance_interval'),
        ),
        migrations.AlterField(
            model_name='webcam',
            name='maintenance_report',
            field=models.ImageField(blank=True, null=True, upload_to=security_system.models.maintenance_report_directory_path, verbose_name='maintenance_report'),
        ),
        migrations.AlterField(
            model_name='webcam',
            name='receipt_date',
            field=models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='receipt_date'),
        ),
        migrations.AlterField(
            model_name='webcam',
            name='service_date',
            field=models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='service_date'),
        ),
        migrations.AlterField(
            model_name='webcam',
            name='service_date_next',
            field=models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='service_date_next'),
        ),
    ]
