# Generated by Django 4.2.2 on 2023-06-24 19:12

from django.db import migrations, models
import document.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='name')),
                ('series_and_number', models.CharField(db_index=True, max_length=30, verbose_name='series_and_number')),
                ('date_issue', models.CharField(db_index=True, max_length=10, verbose_name='date_issue')),
                ('date_expiration', models.CharField(db_index=True, max_length=10, verbose_name='date_expiration')),
                ('who_issued', models.CharField(db_index=True, max_length=50, verbose_name='who_issued')),
                ('place_registration', models.CharField(db_index=True, max_length=150, verbose_name='place_registration')),
                ('place_of_residence', models.CharField(db_index=True, max_length=150, verbose_name='place_of_residence')),
                ('driving_license_categories', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='driving_license_categories')),
                ('document_copy', models.ImageField(blank=True, null=True, upload_to=document.models.document_directory_path, verbose_name='document_copy')),
            ],
        ),
    ]
