# Generated by Django 4.2.2 on 2023-06-26 20:41

from django.db import migrations, models
import document.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Briefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='name_briefing')),
                ('description', models.TextField(db_index=True, verbose_name='description_briefing')),
                ('data_briefing', models.CharField(db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, verbose_name='data_briefing')),
                ('committee_chair', models.CharField(db_index=True, max_length=30, verbose_name='committee_chair')),
                ('briefing_report', models.ImageField(blank=True, null=True, upload_to=document.models.briefing_report_directory_path, verbose_name='briefing_report')),
                ('data_next_briefing', models.CharField(db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, verbose_name='data_next_briefing')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='name_document')),
                ('series_and_number', models.CharField(db_index=True, help_text='format: series number', max_length=30, verbose_name='series_and_number_document')),
                ('date_issue', models.CharField(db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, verbose_name='date_issue_document')),
                ('date_expiration', models.CharField(db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, verbose_name='date_expiration_document')),
                ('who_issued', models.CharField(db_index=True, max_length=50, verbose_name='who_issued_document')),
                ('place_registration', models.CharField(db_index=True, max_length=150, verbose_name='place_registration_document')),
                ('driving_license_categories', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='driving_license_categories_document')),
                ('document_copy', models.ImageField(blank=True, null=True, upload_to=document.models.document_directory_path, verbose_name='document_copy')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
