# Generated by Django 4.2.2 on 2023-06-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_expiration',
            field=models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='date_expiration_document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='driving_license_categories',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='driving_license_categories_document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='place_registration',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='place_registration_document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='who_issued',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='who_issued_document'),
        ),
    ]
