# Generated by Django 4.2.2 on 2023-06-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_alter_document_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_expiration',
            field=models.CharField(db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, verbose_name='date_expiration'),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_issue',
            field=models.CharField(db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, verbose_name='date_issue'),
        ),
        migrations.AlterField(
            model_name='document',
            name='series_and_number',
            field=models.CharField(db_index=True, help_text='format data: dd.mm.yyyy', max_length=30, verbose_name='series_and_number'),
        ),
    ]
