# Generated by Django 4.2.2 on 2023-06-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_alter_document_date_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='series_and_number',
            field=models.CharField(db_index=True, help_text='format: series number', max_length=30, verbose_name='series_and_number'),
        ),
    ]
