# Generated by Django 4.2.2 on 2023-06-24 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_alter_document_series_and_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='place_of_residence',
        ),
    ]
