# Generated by Django 4.2.2 on 2023-06-24 19:12

import briefing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Briefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='name')),
                ('description', models.TextField(db_index=True, verbose_name='description')),
                ('data_briefing', models.CharField(db_index=True, max_length=10, verbose_name='data_briefing')),
                ('committee_chair', models.CharField(db_index=True, max_length=30, verbose_name='committee_chair')),
                ('briefing_report', models.ImageField(blank=True, null=True, upload_to=briefing.models.briefing_report_directory_path, verbose_name='preview')),
                ('data_next_briefing', models.CharField(db_index=True, max_length=10, verbose_name='data_briefing')),
            ],
        ),
    ]
