# Generated by Django 4.2.2 on 2023-06-28 19:37

from django.db import migrations, models
import vehicle.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('worker', '0001_initial'),
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='name_vehicle')),
                ('branding', models.BooleanField(default=False)),
                ('VIN_number', models.CharField(db_index=True, max_length=20, verbose_name='VIN_number')),
                ('license_plate', models.CharField(db_index=True, max_length=20, verbose_name='license_plate')),
                ('date_manufacture', models.CharField(db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, verbose_name='date_manufacture')),
                ('date_purchase', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='date_purchase')),
                ('registration_certificate_number', models.CharField(db_index=True, max_length=20, verbose_name='registration_certificate_number')),
                ('reg_certificate_number_copy', models.ImageField(blank=True, null=True, upload_to=vehicle.models.reg_certificate_number_copy_directory_path, verbose_name='reg_certificate_number_copy')),
                ('passport_number', models.CharField(db_index=True, help_text='format number: 1234 123456', max_length=11, verbose_name='passport_number')),
                ('number_insurance_policy', models.CharField(db_index=True, max_length=20, verbose_name='number_insurance_policy')),
                ('date_expiration_insurance', models.ImageField(blank=True, null=True, upload_to=vehicle.models.insurance_policy_directory_path, verbose_name='insurance_policy')),
                ('mileage', models.PositiveIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='mileage')),
                ('service_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='service_date_vehicle')),
                ('engine_oil', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='engine_oil')),
                ('armors', models.ManyToManyField(related_name='armors_vehicle', to='equipment.armor', verbose_name='armors')),
                ('is_listed_insurance', models.ManyToManyField(related_name='is_listed_insurance', to='worker.worker', verbose_name='is_listed_insurance')),
                ('passport_copy', models.ManyToManyField(related_name='passport_copy_vehicle', to='document.document', verbose_name='passport_vehicle')),
                ('radio_stations', models.ManyToManyField(related_name='radio_stations_vehicle', to='equipment.radio_station', verbose_name='radio_stations')),
                ('video_recorders', models.ManyToManyField(related_name='video_recorders_vehicle', to='equipment.video_recorder', verbose_name='video_recorders')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
    ]
