# Generated by Django 4.2.2 on 2023-07-02 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('worker', '0001_initial'),
        ('document', '0001_initial'),
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='name')),
                ('branding', models.BooleanField(default=False)),
                ('VIN_number', models.CharField(db_index=True, max_length=20, verbose_name='VIN_number')),
                ('license_plate', models.CharField(db_index=True, max_length=20, verbose_name='license_plate')),
                ('date_manufacture', models.CharField(db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, verbose_name='date_manufacture')),
                ('date_purchase', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='date_purchase')),
                ('insurance_policy_limit', models.CharField(choices=[('without limitation', 'without limitation'), ('limited', 'limited')], db_index=True, default='without limitation', max_length=18, verbose_name='policy_limit')),
                ('date_expiration_insurance', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='date_expiration_insurance')),
                ('mileage', models.PositiveIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='mileage')),
                ('service_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='service_date')),
                ('engine_oil', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='engine_oil')),
                ('engine_oil_viscosity', models.CharField(choices=[('0W-20', '0W-20'), ('0W-30', '0W-30'), ('0W-40', '0W-40'), ('5W-20', '5W-20'), ('5W-30', '5W-30'), ('5W-40', '5W-40'), ('10W-20', '10W-20'), ('10W-30', '10W-30'), ('10W-40', '10W-40'), ('15W-30', '15W-30'), ('15W-40', '15W-40'), ('20W-30', '20W-30'), ('20W-40', '20W-40')], db_index=True, default='5W-40', max_length=6, verbose_name='oil_viscosity')),
                ('armors', models.ManyToManyField(related_name='armors_vehicle', to='equipment.armor', verbose_name='armors')),
                ('insurance_policy_copy', models.ManyToManyField(related_name='insurance_policy_copy', to='document.document', verbose_name='insurance_policy')),
                ('is_listed_insurance', models.ManyToManyField(related_name='is_listed_insurance', to='worker.worker', verbose_name='is_listed_insurance')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.affiliated_company')),
                ('passport_copy', models.ManyToManyField(related_name='passport_copy_vehicle', to='document.document', verbose_name='passport')),
                ('radio_stations', models.ManyToManyField(related_name='radio_stations_vehicle', to='equipment.radio_station', verbose_name='radio_stations')),
                ('registration_certificate', models.ManyToManyField(related_name='registration_certificate', to='document.document', verbose_name='registration_certificate')),
                ('video_recorders', models.ManyToManyField(related_name='video_recorders_vehicle', to='equipment.video_recorder', verbose_name='video_recorders')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
    ]
