# Generated by Django 4.2.2 on 2023-06-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='passport_copy',
            field=models.ManyToManyField(related_name='passport_copy_vehicle', to='document.document', verbose_name='passport_vehicle'),
        ),
    ]
