# Generated by Django 4.2.2 on 2023-06-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='engine_oil_viscosity',
            field=models.CharField(choices=[('0W-20', '0W-20'), ('0W-30', '0W-30'), ('0W-40', '0W-40'), ('5W-20', '5W-20'), ('5W-30', '5W-30'), ('5W-40', '5W-40'), ('10W-20', '10W-20'), ('10W-30', '10W-30'), ('10W-40', '10W-40'), ('15W-30', '15W-30'), ('15W-40', '15W-40'), ('20W-30', '20W-30'), ('20W-40', '20W-40')], db_index=True, default='5W-40', max_length=6, verbose_name='oil_viscosity'),
        ),
    ]
