# Generated by Django 4.2.2 on 2023-06-28 15:56

from django.db import migrations, models
import vehicle.models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
        ('vehicle', '0003_alter_vehicle_vin_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='date_expiration_insurance',
            field=models.ImageField(blank=True, null=True, upload_to=vehicle.models.insurance_policy_directory_path, verbose_name='insurance_policy'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='date_manufacture',
            field=models.CharField(db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, verbose_name='date_manufacture'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='date_purchase',
            field=models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='date_purchase'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_oil',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='engine_oil'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='is_listed_insurance',
            field=models.ManyToManyField(related_name='is_listed_insurance', to='worker.worker', verbose_name='is_listed_insurance'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(db_index=True, max_length=20, verbose_name='license_plate'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='mileage'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='number_insurance_policy',
            field=models.CharField(db_index=True, max_length=20, verbose_name='number_insurance_policy'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='passport_number',
            field=models.CharField(db_index=True, help_text='format number: 1234 123456', max_length=11, verbose_name='passport_number'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='reg_certificate_number_copy',
            field=models.ImageField(blank=True, null=True, upload_to=vehicle.models.reg_certificate_number_copy_directory_path, verbose_name='reg_certificate_number_copy'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_certificate_number',
            field=models.CharField(db_index=True, max_length=20, verbose_name='registration_certificate_number'),
        ),
    ]
