# Generated by Django 4.2.2 on 2023-06-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_radio_station'),
        ('vehicle', '0004_alter_vehicle_date_expiration_insurance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='armors',
            field=models.ManyToManyField(related_name='armors', to='equipment.armor', verbose_name='armors'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='radio_stations',
            field=models.ManyToManyField(related_name='radio_stations', to='equipment.radio_station', verbose_name='radio_stations'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='video_recorders',
            field=models.ManyToManyField(related_name='video_recorders', to='equipment.video_recorder', verbose_name='video_recorders'),
        ),
    ]
