# Generated by Django 4.2.2 on 2023-06-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_radio_station'),
        ('vehicle', '0005_vehicle_armors_vehicle_radio_stations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='armors',
            field=models.ManyToManyField(related_name='armors_vehicle', to='equipment.armor', verbose_name='armors'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='radio_stations',
            field=models.ManyToManyField(related_name='radio_stations_vehicle', to='equipment.radio_station', verbose_name='radio_stations'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='video_recorders',
            field=models.ManyToManyField(related_name='video_recorders_vehicle', to='equipment.video_recorder', verbose_name='video_recorders'),
        ),
    ]
