# Generated by Django 4.2.2 on 2023-06-28 19:21

from django.db import migrations, models
import django.db.models.deletion
import protected_object.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0005_radio_station'),
        ('vehicle', '0005_vehicle_armors_vehicle_radio_stations_and_more'),
        ('security_system', '0002_alter_alarm_system_certificate_and_more'),
        ('worker', '0002_alter_worker_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='name')),
                ('address', models.CharField(db_index=True, max_length=100, verbose_name='address')),
                ('phone', models.PositiveBigIntegerField(blank=True, db_index=True, default=0, help_text='format phone: 83517772233', max_length=11, null=True, verbose_name='phone')),
                ('email', models.EmailField(max_length=254)),
                ('INN', models.PositiveBigIntegerField(db_index=True, default=0, max_length=12, verbose_name='INN')),
                ('OGRN', models.PositiveBigIntegerField(db_index=True, default=0, max_length=15, verbose_name='OGRN')),
                ('bank_details', models.CharField(blank=True, max_length=200, null=True, verbose_name='bank_details')),
                ('director', models.CharField(db_index=True, max_length=75, verbose_name='director')),
                ('contact_person', models.CharField(db_index=True, max_length=75, verbose_name='contact_person')),
                ('phone_contact_person', models.PositiveBigIntegerField(blank=True, db_index=True, default=0, help_text='format phone: 83517772233', max_length=11, null=True, verbose_name='phone_contact_person')),
                ('security_contracts', models.ImageField(blank=True, null=True, upload_to=protected_object.models.security_contracts_directory_path, verbose_name='security_contracts')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='name')),
                ('security_time', models.CharField(db_index=True, max_length=20, verbose_name='security_time')),
                ('start_day_shift', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=5, null=True, verbose_name='start_day_shift')),
                ('start_night_shift', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=5, null=True, verbose_name='start_night_shift')),
                ('phone', models.PositiveBigIntegerField(blank=True, db_index=True, default=0, help_text='format phone: 83517772233', max_length=11, null=True, verbose_name='phone')),
                ('number_per_day', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='number_per_day')),
                ('number_per_night', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='number_per_night')),
                ('alarm_systems', models.ManyToManyField(related_name='alarm_systems_post', to='security_system.alarm_system', verbose_name='alarm_systems')),
                ('armors', models.ManyToManyField(related_name='armors_post', to='equipment.armor', verbose_name='armors')),
                ('guns', models.ManyToManyField(related_name='guns_post', to='equipment.gun', verbose_name='guns')),
                ('radio_stations', models.ManyToManyField(related_name='radio_stations_post', to='equipment.radio_station', verbose_name='radio_stations')),
                ('vehicles', models.ManyToManyField(related_name='vehicles_post', to='vehicle.vehicle', verbose_name='vehicles')),
                ('webcams', models.ManyToManyField(related_name='webcams_post', to='security_system.webcam', verbose_name='webcams')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Protected_object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='name')),
                ('address', models.CharField(db_index=True, max_length=100, verbose_name='address')),
                ('security_method', models.CharField(db_index=True, max_length=50, verbose_name='security_method')),
                ('foto', models.ImageField(blank=True, null=True, upload_to=protected_object.models.protected_object_foto_directory_path, verbose_name='foto')),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worker.worker')),
                ('organizations', models.ManyToManyField(related_name='organizations', to='protected_object.organization', verbose_name='organizations')),
                ('posts', models.ManyToManyField(related_name='posts', to='protected_object.post', verbose_name='posts')),
                ('security_systems', models.ManyToManyField(related_name='security_systems', to='security_system.security_system', verbose_name='security_systems')),
            ],
            options={
                'verbose_name': 'Protected_object',
                'verbose_name_plural': 'Protected_objects',
            },
        ),
    ]
