# Generated by Django 4.2.2 on 2023-07-02 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security_system', '0001_initial'),
        ('vehicle', '0001_initial'),
        ('equipment', '0001_initial'),
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='name')),
                ('address', models.CharField(db_index=True, max_length=100, verbose_name='address')),
                ('phone', models.PositiveBigIntegerField(blank=True, db_index=True, default=0, help_text='format phone: 83517772233', null=True, verbose_name='phone')),
                ('email', models.EmailField(max_length=254)),
                ('INN', models.PositiveBigIntegerField(db_index=True, default=0, verbose_name='INN')),
                ('OGRN', models.PositiveBigIntegerField(db_index=True, default=0, verbose_name='OGRN')),
                ('bank_details', models.CharField(blank=True, max_length=200, null=True, verbose_name='bank_details')),
                ('director', models.CharField(db_index=True, max_length=75, verbose_name='director')),
                ('contact_person', models.CharField(db_index=True, max_length=75, verbose_name='contact_person')),
                ('phone_contact_person', models.PositiveBigIntegerField(blank=True, db_index=True, default=0, help_text='format phone: 83517772233', null=True, verbose_name='phone_contact_person')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='name')),
                ('address', models.CharField(db_index=True, max_length=100, verbose_name='address')),
                ('phone', models.PositiveBigIntegerField(blank=True, db_index=True, default=0, help_text='format phone: 83517772233', null=True, verbose_name='phone')),
                ('email', models.EmailField(max_length=254)),
                ('INN', models.PositiveBigIntegerField(db_index=True, default=0, verbose_name='INN')),
                ('OGRN', models.PositiveBigIntegerField(db_index=True, default=0, verbose_name='OGRN')),
                ('bank_details', models.CharField(blank=True, max_length=200, null=True, verbose_name='bank_details')),
                ('director', models.CharField(db_index=True, max_length=75, verbose_name='director')),
                ('contact_person', models.CharField(db_index=True, max_length=75, verbose_name='contact_person')),
                ('phone_contact_person', models.PositiveBigIntegerField(blank=True, db_index=True, default=0, help_text='format phone: 83517772233', null=True, verbose_name='phone_contact_person')),
            ],
            options={
                'verbose_name': 'Performer',
                'verbose_name_plural': 'Performers',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='name')),
                ('protection_mode', models.CharField(choices=[('round-the-clock', '24/7'), ('daytime', 'Daytime'), ('nightly', 'Nightly'), ('mixed', 'Mixed')], db_index=True, default='24/7', max_length=15, verbose_name='protection_mode')),
                ('start_day_shift', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=5, null=True, verbose_name='start_day_shift')),
                ('start_day_shift_free_day', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=5, null=True, verbose_name='start_day_shift_free_day')),
                ('start_night_shift', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=5, null=True, verbose_name='start_night_shift')),
                ('phone', models.PositiveBigIntegerField(blank=True, db_index=True, default=0, help_text='format phone: 83517772233', null=True, verbose_name='phone')),
                ('number_per_day', models.PositiveSmallIntegerField(blank=True, default=0, help_text='number of guards per day', null=True, verbose_name='number_per_day')),
                ('number_per_night', models.PositiveSmallIntegerField(blank=True, default=0, help_text='number of guards per night', null=True, verbose_name='number_per_night')),
                ('alarm_systems', models.ManyToManyField(related_name='alarm_systems_post', to='security_system.alarm_system', verbose_name='alarm_systems')),
                ('armors', models.ManyToManyField(related_name='armors_post', to='equipment.armor', verbose_name='armors')),
                ('guns', models.ManyToManyField(related_name='guns_post', to='equipment.gun', verbose_name='guns')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='protected_object.performer')),
                ('radio_stations', models.ManyToManyField(related_name='radio_stations_post', to='equipment.radio_station', verbose_name='radio_stations')),
                ('vehicles', models.ManyToManyField(related_name='vehicles_post', to='vehicle.vehicle', verbose_name='vehicles')),
                ('webcams', models.ManyToManyField(related_name='webcams_post', to='security_system.webcam', verbose_name='webcams')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Protected_object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='name')),
                ('address', models.CharField(db_index=True, max_length=100, verbose_name='address')),
                ('security_method', models.CharField(db_index=True, max_length=50, verbose_name='security_method')),
                ('clients', models.ManyToManyField(related_name='organizations', to='protected_object.client', verbose_name='organizations')),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worker.worker')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='protected_object.performer')),
                ('posts', models.ManyToManyField(related_name='posts', to='protected_object.post', verbose_name='posts')),
                ('security_systems', models.ManyToManyField(related_name='security_systems', to='security_system.security_system', verbose_name='security_systems')),
            ],
            options={
                'verbose_name': 'Protected_object',
                'verbose_name_plural': 'Protected_objects',
            },
        ),
    ]
