# Generated by Django 4.2.2 on 2023-06-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protected_object', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='protection_mode',
            field=models.CharField(db_index=True, max_length=20, verbose_name='protection_mode'),
        ),
    ]
