# Generated by Django 4.2.2 on 2023-06-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protected_object', '0002_alter_organization_phone_alter_post_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='INN',
            field=models.PositiveBigIntegerField(db_index=True, default=0, verbose_name='INN'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='OGRN',
            field=models.PositiveBigIntegerField(db_index=True, default=0, verbose_name='OGRN'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone_contact_person',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, default=0, help_text='format phone: 83517772233', null=True, verbose_name='phone_contact_person'),
        ),
    ]
