# Generated by Django 4.2.2 on 2023-06-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protected_object', '0002_alter_post_protection_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='start_day_shift_free_day',
            field=models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=5, null=True, verbose_name='start_day_shift_free_day'),
        ),
        migrations.AlterField(
            model_name='post',
            name='protection_mode',
            field=models.CharField(choices=[('round-the-clock', '24/7'), ('daytime', 'Daytime'), ('nightly', 'Nightly'), ('mixed', 'Mixed')], db_index=True, default='24/7', max_length=15, verbose_name='protection_mode'),
        ),
    ]
