# Generated by Django 4.2.2 on 2023-07-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliated_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='name')),
                ('address', models.CharField(db_index=True, max_length=100, verbose_name='address')),
                ('phone', models.PositiveBigIntegerField(blank=True, db_index=True, default=0, help_text='format phone: 83517772233', null=True, verbose_name='phone')),
                ('email', models.EmailField(max_length=254)),
                ('INN', models.PositiveBigIntegerField(db_index=True, default=0, verbose_name='INN')),
                ('OGRN', models.PositiveBigIntegerField(db_index=True, default=0, verbose_name='OGRN')),
                ('bank_details', models.CharField(blank=True, max_length=200, null=True, verbose_name='bank_details')),
                ('director', models.CharField(db_index=True, max_length=75, verbose_name='director')),
                ('contact_person', models.CharField(db_index=True, max_length=75, verbose_name='contact_person')),
                ('phone_contact_person', models.PositiveBigIntegerField(blank=True, db_index=True, default=0, help_text='format phone: 83517772233', null=True, verbose_name='phone_contact_person')),
            ],
            options={
                'verbose_name': 'Affiliated_company',
                'verbose_name_plural': 'Affiliated_companies',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='name')),
                ('manager', models.CharField(db_index=True, max_length=75, verbose_name='manager')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
            },
        ),
    ]
