# Generated by Django 4.2.2 on 2023-06-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uniform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='name')),
                ('description', models.CharField(db_index=True, max_length=100, verbose_name='description')),
                ('size', models.SmallIntegerField(blank=True, db_index=True, default=0, verbose_name='size')),
            ],
        ),
    ]
