# Generated by Django 4.2.2 on 2023-06-24 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniform', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uniform',
            options={'verbose_name': 'Uniform', 'verbose_name_plural': 'Uniforms'},
        ),
    ]
