# Generated by Django 4.2.2 on 2023-06-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniform', '0002_alter_uniform_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniform',
            name='size',
            field=models.SmallIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='size'),
        ),
    ]
