# Generated by Django 4.2.2 on 2023-07-02 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_recorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='name_video_recorder')),
                ('description', models.CharField(db_index=True, max_length=100, verbose_name='description_video_recorder')),
                ('factory_number', models.CharField(db_index=True, max_length=15, verbose_name='factory_number_video_recorder')),
                ('installation_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='installation_date_video_recorder')),
                ('maintenance_interval', models.CharField(db_index=True, help_text='number of months: XX', max_length=15, verbose_name='maintenance_interval_video_recorder')),
                ('date_manufacture', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='date_manufacture_video_recorder')),
                ('receipt_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='receipt_date_video_recorder')),
                ('service_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='service_date_video_recorder')),
                ('service_date_next', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='service_date_next_video_recorder')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.affiliated_company')),
            ],
            options={
                'verbose_name': 'Video_recorder',
                'verbose_name_plural': 'Video_recorders',
            },
        ),
        migrations.CreateModel(
            name='Uniform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='name_uniform')),
                ('description', models.CharField(db_index=True, max_length=100, verbose_name='description_uniform')),
                ('size', models.SmallIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='size_uniform')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.affiliated_company')),
            ],
            options={
                'verbose_name': 'Uniform',
                'verbose_name_plural': 'Uniforms',
            },
        ),
        migrations.CreateModel(
            name='Special_spray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='name_special_spray')),
                ('description', models.CharField(db_index=True, max_length=100, verbose_name='description__special_spray')),
                ('date_manufacture', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='date_manufacture__special_spray')),
                ('expiration_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='expiration_date_special_spray')),
                ('receipt_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='receipt_date_special_spray')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.affiliated_company')),
            ],
            options={
                'verbose_name': 'Special_spray',
                'verbose_name_plural': 'Special_sprays',
            },
        ),
        migrations.CreateModel(
            name='Rubber_stick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='name_rubber_stick')),
                ('description', models.CharField(db_index=True, max_length=100, verbose_name='description_rubber_stick')),
                ('date_manufacture', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='date_manufacture_rubber_stick')),
                ('receipt_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='receipt_date_rubber_stick')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.affiliated_company')),
            ],
            options={
                'verbose_name': 'Rubber_stick',
                'verbose_name_plural': 'Rubber_sticks',
            },
        ),
        migrations.CreateModel(
            name='Radio_station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='name_radio_station')),
                ('description', models.CharField(db_index=True, max_length=100, verbose_name='description_radio_station')),
                ('factory_number', models.CharField(db_index=True, max_length=15, verbose_name='factory_number_radio_station')),
                ('installation_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='installation_date_radio_station')),
                ('maintenance_interval', models.CharField(blank=True, db_index=True, help_text='number of months: XX', max_length=15, null=True, verbose_name='maintenance_interval_radio_station')),
                ('date_manufacture', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='date_manufacture_radio_station')),
                ('receipt_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='receipt_date_radio_station')),
                ('service_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='service_date_radio_station')),
                ('service_date_next', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='service_date_next_radio_station')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.affiliated_company')),
            ],
            options={
                'verbose_name': 'Radio_station',
                'verbose_name_plural': 'Radio_stations',
            },
        ),
        migrations.CreateModel(
            name='Handcuffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='name_handcuffs')),
                ('description', models.CharField(db_index=True, max_length=100, verbose_name='description_handcuffs')),
                ('factory_number', models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='factory_number_handcuffs')),
                ('date_manufacture', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='date_manufacture_handcuffs')),
                ('receipt_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='receipt_date_handcuffs')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.affiliated_company')),
            ],
            options={
                'verbose_name': 'Handcuffs',
                'verbose_name_plural': 'Handcuffs',
            },
        ),
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='name_gun')),
                ('description', models.CharField(db_index=True, max_length=100, verbose_name='description_gun')),
                ('factory_number', models.CharField(db_index=True, max_length=15, verbose_name='factory_number_gun')),
                ('date_manufacture', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='date_manufacture_gun')),
                ('date_test_shoot', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='date_test_shoot')),
                ('receipt_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='receipt_date_gun')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.affiliated_company')),
            ],
            options={
                'verbose_name': 'Gun',
                'verbose_name_plural': 'Guns',
            },
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=15, verbose_name='name_armor')),
                ('description', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='description_armor')),
                ('factory_number', models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='factory_number_armor')),
                ('date_manufacture', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='date_manufacture_armor')),
                ('protection_category', models.SmallIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='protection_category_armor')),
                ('date_purchase', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='date_purchase_armor')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='config.affiliated_company')),
            ],
            options={
                'verbose_name': 'Armor',
                'verbose_name_plural': 'Armors',
            },
        ),
    ]
