# Generated by Django 4.2.2 on 2023-06-26 20:41

from django.db import migrations, models
import equipment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=15, verbose_name='name_armor')),
                ('description', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='description_armor')),
                ('factory_number', models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='factory_number_armor')),
                ('date_manufacture', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='date_manufacture_armor')),
                ('protection_category', models.SmallIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='protection_category_armor')),
                ('date_purchase', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='date_purchase_armor')),
                ('certificate', models.ImageField(blank=True, null=True, upload_to=equipment.models.certificate_directory_path, verbose_name='certificate_armor')),
            ],
            options={
                'verbose_name': 'Armor',
                'verbose_name_plural': 'Armors',
            },
        ),
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='name_gun')),
                ('description', models.CharField(db_index=True, max_length=100, verbose_name='description_gun')),
                ('factory_number', models.CharField(db_index=True, max_length=15, verbose_name='factory_number_gun')),
                ('date_manufacture', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='date_manufacture_gun')),
                ('certificate', models.ImageField(blank=True, null=True, upload_to=equipment.models.certificate_directory_path, verbose_name='certificate_gun')),
                ('date_test_shoot', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='date_test_shoot')),
                ('receipt_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='receipt_date_gun')),
            ],
            options={
                'verbose_name': 'Gun',
                'verbose_name_plural': 'Guns',
            },
        ),
        migrations.CreateModel(
            name='Uniform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='name_uniform')),
                ('description', models.CharField(db_index=True, max_length=100, verbose_name='description_uniform')),
                ('size', models.SmallIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='size_uniform')),
            ],
            options={
                'verbose_name': 'Uniform',
                'verbose_name_plural': 'Uniforms',
            },
        ),
    ]
