# Generated by Django 4.2.2 on 2023-06-26 21:02

from django.db import migrations, models
import equipment.models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_recorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='name_video_recorder')),
                ('description', models.CharField(db_index=True, max_length=100, verbose_name='description_video_recorder')),
                ('factory_number', models.CharField(db_index=True, max_length=15, verbose_name='factory_number_video_recorder')),
                ('certificate', models.ImageField(blank=True, null=True, upload_to=equipment.models.certificate_directory_path, verbose_name='certificate_video_recorder')),
                ('installation_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='installation_date_video_recorder')),
                ('maintenance_interval', models.CharField(db_index=True, max_length=15, verbose_name='maintenance_interval_video_recorder')),
                ('date_manufacture', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='date_manufacture_video_recorder')),
                ('receipt_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='receipt_date_video_recorder')),
                ('service_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='service_date_video_recorder')),
                ('service_date_next', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='service_date_next_video_recorder')),
                ('maintenance_report', models.ImageField(blank=True, null=True, upload_to=equipment.models.maintenance_report_directory_path, verbose_name='maintenance_report_video_recorder')),
            ],
            options={
                'verbose_name': 'Video_recorder',
                'verbose_name_plural': 'Video_recorders',
            },
        ),
    ]
