# Generated by Django 4.2.2 on 2023-06-26 21:20

from django.db import migrations, models
import equipment.models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_video_recorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handcuffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='name_handcuffs')),
                ('description', models.CharField(db_index=True, max_length=100, verbose_name='description_handcuffs')),
                ('factory_number', models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='factory_number_handcuffs')),
                ('date_manufacture', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='date_manufacture_handcuffs')),
                ('certificate', models.ImageField(blank=True, null=True, upload_to=equipment.models.certificate_directory_path, verbose_name='certificate_handcuffs')),
                ('receipt_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='receipt_date_handcuffs')),
            ],
            options={
                'verbose_name': 'Handcuffs',
                'verbose_name_plural': 'Handcuffs',
            },
        ),
        migrations.CreateModel(
            name='Rubber_stick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='name_rubber_stick')),
                ('description', models.CharField(db_index=True, max_length=100, verbose_name='description_rubber_stick')),
                ('date_manufacture', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='date_manufacture_rubber_stick')),
                ('certificate', models.ImageField(blank=True, null=True, upload_to=equipment.models.certificate_directory_path, verbose_name='certificate_rubber_stick')),
                ('receipt_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='receipt_date_rubber_stick')),
            ],
            options={
                'verbose_name': 'Rubber_stick',
                'verbose_name_plural': 'Rubber_sticks',
            },
        ),
    ]
