# Generated by Django 4.2.2 on 2023-06-26 22:21

from django.db import migrations, models
import equipment.models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_handcuffs_rubber_stick'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special_spray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='name_special_spray')),
                ('description', models.CharField(db_index=True, max_length=100, verbose_name='description__special_spray')),
                ('date_manufacture', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='date_manufacture__special_spray')),
                ('expiration_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='expiration_date_special_spray')),
                ('certificate', models.ImageField(blank=True, null=True, upload_to=equipment.models.certificate_directory_path, verbose_name='certificate_special_spray')),
                ('receipt_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='receipt_date_special_spray')),
            ],
            options={
                'verbose_name': 'Special_spray',
                'verbose_name_plural': 'Special_sprays',
            },
        ),
    ]
