# Generated by Django 4.2.2 on 2023-06-26 23:32

from django.db import migrations, models
import equipment.models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_special_spray'),
    ]

    operations = [
        migrations.CreateModel(
            name='Radio_station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='name_radio_station')),
                ('description', models.CharField(db_index=True, max_length=100, verbose_name='description_radio_station')),
                ('factory_number', models.CharField(db_index=True, max_length=15, verbose_name='factory_number_radio_station')),
                ('certificate', models.ImageField(blank=True, null=True, upload_to=equipment.models.certificate_directory_path, verbose_name='certificate_radio_station')),
                ('installation_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='installation_date_radio_station')),
                ('maintenance_interval', models.CharField(db_index=True, max_length=15, verbose_name='maintenance_interval_radio_station')),
                ('date_manufacture', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='date_manufacture_radio_station')),
                ('receipt_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='receipt_date_radio_station')),
                ('service_date', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='service_date_radio_station')),
                ('service_date_next', models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='service_date_next_radio_station')),
                ('maintenance_report', models.ImageField(blank=True, null=True, upload_to=equipment.models.maintenance_report_directory_path, verbose_name='maintenance_report_radio_station')),
            ],
            options={
                'verbose_name': 'Radio_station',
                'verbose_name_plural': 'Radio_stations',
            },
        ),
    ]
