# Generated by Django 4.2.2 on 2023-06-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gun',
            name='date_manufacture',
            field=models.CharField(blank=True, db_index=True, help_text='format data: dd.mm.yyyy', max_length=10, null=True, verbose_name='date_manufacture'),
        ),
    ]
